###Authorization token should get from a login person access token or register person access token
GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDUwNDE1NDIsImV4cCI6MTcwNTA0MTU3MiwiYXVkIjoiNjU5ZmFlZjg2MjE3ZWRlZTY5MzIyZjk1IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.6JBnac1z5JnkzX__UzVamyrDQ8iRQrtlb7TmVVnMg80

###Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "manishakl@gmail.com",
    "password": "1234"
}

###Register

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "manisakl@gmail.com",
    "password": "1234"
}


###Logout
DELETE  http://localhost:3000/auth/logout

###Refresh Token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDUwNDE1NDIsImV4cCI6MTczNjU5OTE0MiwiYXVkIjoiNjU5ZmFlZjg2MjE3ZWRlZTY5MzIyZjk1IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.SlviIfCI6Nd4kvSSIC_4PaDk2O0naPSp-iOgr7h7XsM"
}
